#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

void dispInit();
void dispApplyPendingMode(void);
void dispSetRotate180(bool rotate180);
void dispConsoleInit();
void dispConsoleClear();
void dispConsolePrintf(const char *fmt, ...);
// Append one formatted line using inverse video.
void dispConsolePrintfInverse(const char *fmt, ...);
// Replace one console row without moving the console cursor.
void dispConsoleWriteRow(uint8_t row, bool inverse, const char *fmt, ...);
void dispConsoleSetStatus(const char *fmt, ...);
void dispConsoleSetAutoStatus(const char *fmt, ...);
bool dispConsoleShowQrCode(const char *title, const char *url, const char *hint);
void dispConsoleHideQrCode(void);
void dispShowConsole();
void dispShowEmu();
// Suppress periodic status updates while a modal menu owns the status row.
void dispSetAutoStatusEnabled(bool enabled);
// Temporarily route BOOT-button gestures to a modal boot menu.
void dispSetButtonMenuMode(bool enabled);
// Return 1 for a short press, 2 for a long press, or 0 on timeout.
int dispWaitButtonEvent(uint32_t timeoutMs);
// Check the current active-low BOOT-button level.
bool dispBootButtonPressed();
// Consume a disk-menu request generated by a long press on the console view.
bool dispTakeStorageMenuRequest();

#ifdef __cplusplus
}
#endif
